import «Adic spaces».AdicCompletionBridge
import «Adic spaces».AdicCompletionFaithfullyFlat
import «Adic spaces».AdicCompletionNoetherian
import «Adic spaces».AdicCompletionTransfer
import «Adic spaces».AffinoidTransport
import «Adic spaces».CompletionLocalization
import «Adic spaces».CompletionModelIndependence
import «Adic spaces».SheafyRingEquivTransport
import «Adic spaces».SheafyCompletionModel
import «Adic spaces».SpaRationalSubsetCorrespondence
import «Adic spaces».PresheafAdicCompletion
import «Adic spaces».AdicConvergence
import «Adic spaces».ArtinReesConvergence
import «Adic spaces».AdicMorphisms
import «Adic spaces».AdicMorphismsCore
import «Adic spaces».AdicSpectrum
import «Adic spaces».AlmostMathematics
import «Adic spaces».CechCohomology
import «Adic spaces».AnalyticPoints
import «Adic spaces».AffinoidRings
import «Adic spaces».Basic
import «Adic spaces».BivariateContinuity
import «Adic spaces».Bounded
import «Adic spaces».CoherentRing
import «Adic spaces».CompletedAlgClosure
import «Adic spaces».CompletionExact
import «Adic spaces».CompletedResidueField
import «Adic spaces».CompleteTopCommRingCat
import «Adic spaces».ContinuousValuations
import «Adic spaces».Cor732
import «Adic spaces».Cor832
import «Adic spaces».EmbeddingTopo
import «Adic spaces».ExcellentRing
import «Adic spaces».FaithfulLocLift
import «Adic spaces».FarguesFontaine
import «Adic spaces».FlatnessResults
import «Adic spaces».GeometricReduction
import «Adic spaces».GeometricSeries
import «Adic spaces».HubnerSeparation
import «Adic spaces».HuberRings
import «Adic spaces».PresheafFunctoriality
import «Adic spaces».QuotientTate
import «Adic spaces».IdealClosedness
import «Adic spaces».IdealLocalization
import «Adic spaces».IdealLocalizationCompletion
import «Adic spaces».IntegralStructureSheaf
import «Adic spaces».Example638
import «Adic spaces».IteratedOverlapEquiv
import «Adic spaces».IteratedRational
import «Adic spaces».LaurentBaireSupport
import «Adic spaces».LaurentCoverExact
import «Adic spaces».LaurentCoverTopology
import «Adic spaces».LaneAReverseRoundTrip
import «Adic spaces».LaurentMinusNormalized
import «Adic spaces».LaurentOverlap
import «Adic spaces».LaurentOverlapConsumer
import «Adic spaces».LaurentRefinementCore
import «Adic spaces».LaurentRefinementAcyclic
import «Adic spaces».Lemma745
import «Adic spaces».LocalBasis
import «Adic spaces».LocalizationTopology
import «Adic spaces».NoetherianTateModules
import «Adic spaces».OpenIdeals
import «Adic spaces».OpenMapping
import «Adic spaces».OrderedGroupConvex
import «Adic spaces».PerfectoidRing
import «Adic spaces».PerfectoidSpace
import «Adic spaces».Presheaf
import «Adic spaces».PresheafIdentification
import «Adic spaces».Prop752
import «Adic spaces».PresheafTateStructure
import «Adic spaces».PseudoUniformizer
import «Adic spaces».RationalRefinement
import «Adic spaces».RationalSubsets
import «Adic spaces».RelativeRationalLocData
import «Adic spaces».RelativeStandardRefinement
import «Adic spaces».RestrictionFlatness
import «Adic spaces».LaurentRefinement
import «Adic spaces».LaurentRefinementTree
import «Adic spaces».LaurentSeparationPresheaf
import «Adic spaces».RestrictedPowerSeries
import «Adic spaces».RestrictedModule
import «Adic spaces».RingEquivPresheafTransport
import «Adic spaces».SeminormalRing
import «Adic spaces».CharacteristicSubgroup
import «Adic spaces».SheafyEndpoints
import «Adic spaces».SpaCompact
import «Adic spaces».SpaCompactNoHArch
import «Adic spaces».SpaParameterPerturbation
import «Adic spaces».SpaQCviaSpvAI
import «Adic spaces».ExampleLaurentSeries
import «Adic spaces».ExampleUnitDisc
import «Adic spaces».FJP.FiniteJetMain
import «Adic spaces».FJP.FiniteJetSheafyEndpoints
import «Adic spaces».SpaRationalOpenComparison
import «Adic spaces».SpaRationalOpenHomeomorph
import «Adic spaces».SpaSpanPerturbation
import «Adic spaces».Vendored.XiaMvPowerSeriesEquiv
import «Adic spaces».Vendored.CoramMvRestricted
import «Adic spaces».Vendored.CoramMvGaussNorm
import «Adic spaces».Vendored.CoramMvRestrictedNorm
import «Adic spaces».Vendored.CoramRestrictedNorm
import «Adic spaces».Vendored.CoramRestrictedIso

import «Adic spaces».SpvAI
import «Adic spaces».SpvAITopology
import «Adic spaces».SpvCompletionExtension
import «Adic spaces».StandardCover
import «Adic spaces».RationalIntersection
import «Adic spaces».SheafyFoundations
import «Adic spaces».RationalBasis
import «Adic spaces».StructurePresheafLimit
import «Adic spaces».SheafyPair
import «Adic spaces».SheafyRing
import «Adic spaces».StandardRefinement
import «Adic spaces».StandardDescent
import «Adic spaces».RelativeDescent
import «Adic spaces».StronglyNoetherianTransport
import «Adic spaces».HomSheafPredicate
import «Adic spaces».StructurePresheafBundled
import «Adic spaces».AdicSpaceMorphisms
import «Adic spaces».StructureSheaf
import «Adic spaces».TateAcyclicity
import «Adic spaces».TateAcyclicityFinalAssembly
import «Adic spaces».TateAcyclicityResiduals
import «Adic spaces».TateAlgebra
import «Adic spaces».TateAlgebraTopology
import «Adic spaces».TateAlgebraWedhorn
import «Adic spaces».MvTateAlgebraTopology
import «Adic spaces».WedhornCechAcyclicity
import «Adic spaces».LeafAChainAssembly
import «Adic spaces».Tilting
import «Adic spaces».Uniform
import «Adic spaces».UniformBanach
import «Adic spaces».ValuationAction
import «Adic spaces».ValuationCoarsening
import «Adic spaces».ValuationContinuity
import «Adic spaces».ValuationPrimeConvex
import «Adic spaces».ValuationSpectrum
import «Adic spaces».ValuationSpectrumCompact
import «Adic spaces».ValuativeRel.Comap
import «Adic spaces».WittVectorPrimitive
-- Wedhorn 6.18 chain (planning skeleton, audit-pass-2 proof providers)
import «Adic spaces».BanachOMT
import «Adic spaces».WedhornBanachTheorem
import «Adic spaces».WedhornStronglyNoetherian
import «Adic spaces».AuditCleanWrappers
-- Nonarchimedean Scottish Book (Kedlaya et al., 2015–2022)
-- Described (docstring only, no Lean formalization yet)
import «Adic spaces».ScottishBook.Described.Problem011
import «Adic spaces».ScottishBook.Described.Problem016
import «Adic spaces».ScottishBook.Described.Problem018
import «Adic spaces».ScottishBook.Described.Problem040
-- Stated (with sorry)
import «Adic spaces».ScottishBook.Stated.Problem001
import «Adic spaces».ScottishBook.Stated.Problem002
import «Adic spaces».ScottishBook.Stated.Problem003
import «Adic spaces».ScottishBook.Stated.Problem004
import «Adic spaces».ScottishBook.Stated.Problem005
import «Adic spaces».ScottishBook.Stated.Problem006
import «Adic spaces».ScottishBook.Stated.Problem007
import «Adic spaces».ScottishBook.Stated.Problem008
import «Adic spaces».ScottishBook.Stated.Problem009
import «Adic spaces».ScottishBook.Stated.Problem010
import «Adic spaces».ScottishBook.Stated.Problem012
import «Adic spaces».ScottishBook.Stated.Problem013
import «Adic spaces».ScottishBook.Stated.Problem014
import «Adic spaces».ScottishBook.Stated.Problem015
import «Adic spaces».ScottishBook.Stated.Problem017
import «Adic spaces».ScottishBook.Stated.Problem019
import «Adic spaces».ScottishBook.Stated.Problem020
import «Adic spaces».ScottishBook.Stated.Problem021
import «Adic spaces».ScottishBook.Stated.Problem022
import «Adic spaces».ScottishBook.Stated.Problem023
import «Adic spaces».ScottishBook.Stated.Problem024
import «Adic spaces».ScottishBook.Stated.Problem025
import «Adic spaces».ScottishBook.Stated.Problem026
import «Adic spaces».ScottishBook.Stated.Problem027
import «Adic spaces».ScottishBook.Stated.Problem028
import «Adic spaces».ScottishBook.Stated.Problem029
import «Adic spaces».ScottishBook.Stated.Problem030
import «Adic spaces».ScottishBook.Stated.Problem031
import «Adic spaces».ScottishBook.Stated.Problem032
import «Adic spaces».ScottishBook.Stated.Problem033
import «Adic spaces».ScottishBook.Stated.Problem034
import «Adic spaces».ScottishBook.Stated.Problem035
import «Adic spaces».ScottishBook.Stated.Problem036
import «Adic spaces».ScottishBook.Stated.Problem037
import «Adic spaces».ScottishBook.Stated.Problem038
import «Adic spaces».ScottishBook.Stated.Problem039
import «Adic spaces».WP.Main
-- Modules no other import reaches. Without these the files below build for nobody: they are
-- outside `lake build`'s cone, so they are never compiled and never reach the referee site.
-- Comparator/ stays out on purpose (Challenge.lean is all `sorry` by design), and two modules
-- are left out because they do not compile — `PrimeExtensionClosed` (failed instance synthesis)
-- and `WedhornStage2SpanExtractor` (`Function.mpr`), which between them block 12 more.
import «Adic spaces».CechAcyclicityFull
import «Adic spaces».CechRationalCover
import «Adic spaces».CechRefinementCalculus
import «Adic spaces».FJP.Milnor.StrictMilnorSquare
import «Adic spaces».FJP.Over.ExamplePadic
import «Adic spaces».FJP.Over.LaurentCompat
import «Adic spaces».FJP.Over.StrongSheafy
import «Adic spaces».FJP.RestrictedTruncation
import «Adic spaces».FJP.StrongSheafy
import «Adic spaces».WP.StrongSheafy
import «Adic spaces».Wedhorn834C1SupplierLocalInterface
import «Adic spaces».WedhornC1StrongSupplierBridge
import «Adic spaces».WedhornC1StrongSupplierCore
import «Adic spaces».WedhornC1SupplierLaurentAssembly
import «Adic spaces».WedhornCor732PerTauUpperBoundResidual
import «Adic spaces».WedhornDenominatorClearedCandidate
import «Adic spaces».WedhornMPowerStructuralDataHonestFromCor732
import «Adic spaces».WedhornNormalizedC1AssemblyStrong
import «Adic spaces».WedhornOutsideRescue
import «Adic spaces».WedhornSourceLaurentMembershipInLocalizationBase
import «Adic spaces».WedhornValueGroupLocalizationStrictMono
